// Code generated by MockGen. DO NOT EDIT.
// Source: miner.go
//
// Generated by this command:
//
//	mockgen -source=miner.go -destination=mocks/mock_miner.go -package=mocks Miner
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	url "net/url"
	reflect "reflect"

	commonv1 "github.com/block/proto-fleet/server/generated/grpc/common/v1"
	models "github.com/block/proto-fleet/server/internal/domain/diagnostics/models"
	dto "github.com/block/proto-fleet/server/internal/domain/miner/dto"
	interfaces "github.com/block/proto-fleet/server/internal/domain/miner/interfaces"
	models0 "github.com/block/proto-fleet/server/internal/domain/miner/models"
	models1 "github.com/block/proto-fleet/server/internal/domain/telemetry/models/v2"
	networking "github.com/block/proto-fleet/server/internal/infrastructure/networking"
	sdk "github.com/block/proto-fleet/server/sdk/v1"
	gomock "go.uber.org/mock/gomock"
)

// MockMinerInfo is a mock of MinerInfo interface.
type MockMinerInfo struct {
	ctrl     *gomock.Controller
	recorder *MockMinerInfoMockRecorder
	isgomock struct{}
}

// MockMinerInfoMockRecorder is the mock recorder for MockMinerInfo.
type MockMinerInfoMockRecorder struct {
	mock *MockMinerInfo
}

// NewMockMinerInfo creates a new mock instance.
func NewMockMinerInfo(ctrl *gomock.Controller) *MockMinerInfo {
	mock := &MockMinerInfo{ctrl: ctrl}
	mock.recorder = &MockMinerInfoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMinerInfo) EXPECT() *MockMinerInfoMockRecorder {
	return m.recorder
}

// GetConnectionInfo mocks base method.
func (m *MockMinerInfo) GetConnectionInfo() networking.ConnectionInfo {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetConnectionInfo")
	ret0, _ := ret[0].(networking.ConnectionInfo)
	return ret0
}

// GetConnectionInfo indicates an expected call of GetConnectionInfo.
func (mr *MockMinerInfoMockRecorder) GetConnectionInfo() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetConnectionInfo", reflect.TypeOf((*MockMinerInfo)(nil).GetConnectionInfo))
}

// GetDriverName mocks base method.
func (m *MockMinerInfo) GetDriverName() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDriverName")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetDriverName indicates an expected call of GetDriverName.
func (mr *MockMinerInfoMockRecorder) GetDriverName() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDriverName", reflect.TypeOf((*MockMinerInfo)(nil).GetDriverName))
}

// GetID mocks base method.
func (m *MockMinerInfo) GetID() models0.DeviceIdentifier {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetID")
	ret0, _ := ret[0].(models0.DeviceIdentifier)
	return ret0
}

// GetID indicates an expected call of GetID.
func (mr *MockMinerInfoMockRecorder) GetID() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetID", reflect.TypeOf((*MockMinerInfo)(nil).GetID))
}

// GetOrgID mocks base method.
func (m *MockMinerInfo) GetOrgID() int64 {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOrgID")
	ret0, _ := ret[0].(int64)
	return ret0
}

// GetOrgID indicates an expected call of GetOrgID.
func (mr *MockMinerInfoMockRecorder) GetOrgID() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOrgID", reflect.TypeOf((*MockMinerInfo)(nil).GetOrgID))
}

// GetSerialNumber mocks base method.
func (m *MockMinerInfo) GetSerialNumber() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSerialNumber")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetSerialNumber indicates an expected call of GetSerialNumber.
func (mr *MockMinerInfoMockRecorder) GetSerialNumber() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSerialNumber", reflect.TypeOf((*MockMinerInfo)(nil).GetSerialNumber))
}

// GetSiteID mocks base method.
func (m *MockMinerInfo) GetSiteID() int64 {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSiteID")
	ret0, _ := ret[0].(int64)
	return ret0
}

// GetSiteID indicates an expected call of GetSiteID.
func (mr *MockMinerInfoMockRecorder) GetSiteID() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSiteID", reflect.TypeOf((*MockMinerInfo)(nil).GetSiteID))
}

// GetWebViewURL mocks base method.
func (m *MockMinerInfo) GetWebViewURL() *url.URL {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetWebViewURL")
	ret0, _ := ret[0].(*url.URL)
	return ret0
}

// GetWebViewURL indicates an expected call of GetWebViewURL.
func (mr *MockMinerInfoMockRecorder) GetWebViewURL() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetWebViewURL", reflect.TypeOf((*MockMinerInfo)(nil).GetWebViewURL))
}

// MockMiner is a mock of Miner interface.
type MockMiner struct {
	ctrl     *gomock.Controller
	recorder *MockMinerMockRecorder
	isgomock struct{}
}

// MockMinerMockRecorder is the mock recorder for MockMiner.
type MockMinerMockRecorder struct {
	mock *MockMiner
}

// NewMockMiner creates a new mock instance.
func NewMockMiner(ctrl *gomock.Controller) *MockMiner {
	mock := &MockMiner{ctrl: ctrl}
	mock.recorder = &MockMinerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMiner) EXPECT() *MockMinerMockRecorder {
	return m.recorder
}

// BlinkLED mocks base method.
func (m *MockMiner) BlinkLED(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BlinkLED", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// BlinkLED indicates an expected call of BlinkLED.
func (mr *MockMinerMockRecorder) BlinkLED(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BlinkLED", reflect.TypeOf((*MockMiner)(nil).BlinkLED), ctx)
}

// Curtail mocks base method.
func (m *MockMiner) Curtail(ctx context.Context, req sdk.CurtailRequest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Curtail", ctx, req)
	ret0, _ := ret[0].(error)
	return ret0
}

// Curtail indicates an expected call of Curtail.
func (mr *MockMinerMockRecorder) Curtail(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Curtail", reflect.TypeOf((*MockMiner)(nil).Curtail), ctx, req)
}

// DownloadLogs mocks base method.
func (m *MockMiner) DownloadLogs(ctx context.Context, batchLogUUID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DownloadLogs", ctx, batchLogUUID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DownloadLogs indicates an expected call of DownloadLogs.
func (mr *MockMinerMockRecorder) DownloadLogs(ctx, batchLogUUID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DownloadLogs", reflect.TypeOf((*MockMiner)(nil).DownloadLogs), ctx, batchLogUUID)
}

// FirmwareUpdate mocks base method.
func (m *MockMiner) FirmwareUpdate(ctx context.Context, firmware sdk.FirmwareFile) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FirmwareUpdate", ctx, firmware)
	ret0, _ := ret[0].(error)
	return ret0
}

// FirmwareUpdate indicates an expected call of FirmwareUpdate.
func (mr *MockMinerMockRecorder) FirmwareUpdate(ctx, firmware any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FirmwareUpdate", reflect.TypeOf((*MockMiner)(nil).FirmwareUpdate), ctx, firmware)
}

// GetConnectionInfo mocks base method.
func (m *MockMiner) GetConnectionInfo() networking.ConnectionInfo {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetConnectionInfo")
	ret0, _ := ret[0].(networking.ConnectionInfo)
	return ret0
}

// GetConnectionInfo indicates an expected call of GetConnectionInfo.
func (mr *MockMinerMockRecorder) GetConnectionInfo() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetConnectionInfo", reflect.TypeOf((*MockMiner)(nil).GetConnectionInfo))
}

// GetCoolingMode mocks base method.
func (m *MockMiner) GetCoolingMode(ctx context.Context) (commonv1.CoolingMode, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCoolingMode", ctx)
	ret0, _ := ret[0].(commonv1.CoolingMode)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCoolingMode indicates an expected call of GetCoolingMode.
func (mr *MockMinerMockRecorder) GetCoolingMode(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCoolingMode", reflect.TypeOf((*MockMiner)(nil).GetCoolingMode), ctx)
}

// GetDeviceMetrics mocks base method.
func (m *MockMiner) GetDeviceMetrics(ctx context.Context) (models1.DeviceMetrics, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDeviceMetrics", ctx)
	ret0, _ := ret[0].(models1.DeviceMetrics)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDeviceMetrics indicates an expected call of GetDeviceMetrics.
func (mr *MockMinerMockRecorder) GetDeviceMetrics(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDeviceMetrics", reflect.TypeOf((*MockMiner)(nil).GetDeviceMetrics), ctx)
}

// GetDeviceStatus mocks base method.
func (m *MockMiner) GetDeviceStatus(ctx context.Context) (models0.MinerStatus, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDeviceStatus", ctx)
	ret0, _ := ret[0].(models0.MinerStatus)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDeviceStatus indicates an expected call of GetDeviceStatus.
func (mr *MockMinerMockRecorder) GetDeviceStatus(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDeviceStatus", reflect.TypeOf((*MockMiner)(nil).GetDeviceStatus), ctx)
}

// GetDriverName mocks base method.
func (m *MockMiner) GetDriverName() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDriverName")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetDriverName indicates an expected call of GetDriverName.
func (mr *MockMinerMockRecorder) GetDriverName() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDriverName", reflect.TypeOf((*MockMiner)(nil).GetDriverName))
}

// GetErrors mocks base method.
func (m *MockMiner) GetErrors(ctx context.Context) (models.DeviceErrors, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetErrors", ctx)
	ret0, _ := ret[0].(models.DeviceErrors)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetErrors indicates an expected call of GetErrors.
func (mr *MockMinerMockRecorder) GetErrors(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetErrors", reflect.TypeOf((*MockMiner)(nil).GetErrors), ctx)
}

// GetID mocks base method.
func (m *MockMiner) GetID() models0.DeviceIdentifier {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetID")
	ret0, _ := ret[0].(models0.DeviceIdentifier)
	return ret0
}

// GetID indicates an expected call of GetID.
func (mr *MockMinerMockRecorder) GetID() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetID", reflect.TypeOf((*MockMiner)(nil).GetID))
}

// GetMiningPools mocks base method.
func (m *MockMiner) GetMiningPools(ctx context.Context) ([]interfaces.MinerConfiguredPool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMiningPools", ctx)
	ret0, _ := ret[0].([]interfaces.MinerConfiguredPool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMiningPools indicates an expected call of GetMiningPools.
func (mr *MockMinerMockRecorder) GetMiningPools(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMiningPools", reflect.TypeOf((*MockMiner)(nil).GetMiningPools), ctx)
}

// GetOrgID mocks base method.
func (m *MockMiner) GetOrgID() int64 {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOrgID")
	ret0, _ := ret[0].(int64)
	return ret0
}

// GetOrgID indicates an expected call of GetOrgID.
func (mr *MockMinerMockRecorder) GetOrgID() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOrgID", reflect.TypeOf((*MockMiner)(nil).GetOrgID))
}

// GetSerialNumber mocks base method.
func (m *MockMiner) GetSerialNumber() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSerialNumber")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetSerialNumber indicates an expected call of GetSerialNumber.
func (mr *MockMinerMockRecorder) GetSerialNumber() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSerialNumber", reflect.TypeOf((*MockMiner)(nil).GetSerialNumber))
}

// GetSiteID mocks base method.
func (m *MockMiner) GetSiteID() int64 {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSiteID")
	ret0, _ := ret[0].(int64)
	return ret0
}

// GetSiteID indicates an expected call of GetSiteID.
func (mr *MockMinerMockRecorder) GetSiteID() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSiteID", reflect.TypeOf((*MockMiner)(nil).GetSiteID))
}

// GetWebViewURL mocks base method.
func (m *MockMiner) GetWebViewURL() *url.URL {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetWebViewURL")
	ret0, _ := ret[0].(*url.URL)
	return ret0
}

// GetWebViewURL indicates an expected call of GetWebViewURL.
func (mr *MockMinerMockRecorder) GetWebViewURL() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetWebViewURL", reflect.TypeOf((*MockMiner)(nil).GetWebViewURL))
}

// Reboot mocks base method.
func (m *MockMiner) Reboot(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Reboot", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Reboot indicates an expected call of Reboot.
func (mr *MockMinerMockRecorder) Reboot(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Reboot", reflect.TypeOf((*MockMiner)(nil).Reboot), ctx)
}

// SetCoolingMode mocks base method.
func (m *MockMiner) SetCoolingMode(ctx context.Context, payload dto.CoolingModePayload) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetCoolingMode", ctx, payload)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetCoolingMode indicates an expected call of SetCoolingMode.
func (mr *MockMinerMockRecorder) SetCoolingMode(ctx, payload any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetCoolingMode", reflect.TypeOf((*MockMiner)(nil).SetCoolingMode), ctx, payload)
}

// SetPowerTarget mocks base method.
func (m *MockMiner) SetPowerTarget(ctx context.Context, payload dto.PowerTargetPayload) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetPowerTarget", ctx, payload)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetPowerTarget indicates an expected call of SetPowerTarget.
func (mr *MockMinerMockRecorder) SetPowerTarget(ctx, payload any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetPowerTarget", reflect.TypeOf((*MockMiner)(nil).SetPowerTarget), ctx, payload)
}

// StartMining mocks base method.
func (m *MockMiner) StartMining(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StartMining", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// StartMining indicates an expected call of StartMining.
func (mr *MockMinerMockRecorder) StartMining(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StartMining", reflect.TypeOf((*MockMiner)(nil).StartMining), ctx)
}

// StopMining mocks base method.
func (m *MockMiner) StopMining(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StopMining", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// StopMining indicates an expected call of StopMining.
func (mr *MockMinerMockRecorder) StopMining(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StopMining", reflect.TypeOf((*MockMiner)(nil).StopMining), ctx)
}

// Uncurtail mocks base method.
func (m *MockMiner) Uncurtail(ctx context.Context, req sdk.UncurtailRequest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Uncurtail", ctx, req)
	ret0, _ := ret[0].(error)
	return ret0
}

// Uncurtail indicates an expected call of Uncurtail.
func (mr *MockMinerMockRecorder) Uncurtail(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Uncurtail", reflect.TypeOf((*MockMiner)(nil).Uncurtail), ctx, req)
}

// Unpair mocks base method.
func (m *MockMiner) Unpair(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Unpair", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Unpair indicates an expected call of Unpair.
func (mr *MockMinerMockRecorder) Unpair(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Unpair", reflect.TypeOf((*MockMiner)(nil).Unpair), ctx)
}

// UpdateMinerPassword mocks base method.
func (m *MockMiner) UpdateMinerPassword(ctx context.Context, payload dto.UpdateMinerPasswordPayload) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateMinerPassword", ctx, payload)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateMinerPassword indicates an expected call of UpdateMinerPassword.
func (mr *MockMinerMockRecorder) UpdateMinerPassword(ctx, payload any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateMinerPassword", reflect.TypeOf((*MockMiner)(nil).UpdateMinerPassword), ctx, payload)
}

// UpdateMiningPools mocks base method.
func (m *MockMiner) UpdateMiningPools(ctx context.Context, payload dto.UpdateMiningPoolsPayload) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateMiningPools", ctx, payload)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateMiningPools indicates an expected call of UpdateMiningPools.
func (mr *MockMinerMockRecorder) UpdateMiningPools(ctx, payload any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateMiningPools", reflect.TypeOf((*MockMiner)(nil).UpdateMiningPools), ctx, payload)
}

// MockFirmwareUpdateStatusProvider is a mock of FirmwareUpdateStatusProvider interface.
type MockFirmwareUpdateStatusProvider struct {
	ctrl     *gomock.Controller
	recorder *MockFirmwareUpdateStatusProviderMockRecorder
	isgomock struct{}
}

// MockFirmwareUpdateStatusProviderMockRecorder is the mock recorder for MockFirmwareUpdateStatusProvider.
type MockFirmwareUpdateStatusProviderMockRecorder struct {
	mock *MockFirmwareUpdateStatusProvider
}

// NewMockFirmwareUpdateStatusProvider creates a new mock instance.
func NewMockFirmwareUpdateStatusProvider(ctrl *gomock.Controller) *MockFirmwareUpdateStatusProvider {
	mock := &MockFirmwareUpdateStatusProvider{ctrl: ctrl}
	mock.recorder = &MockFirmwareUpdateStatusProviderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFirmwareUpdateStatusProvider) EXPECT() *MockFirmwareUpdateStatusProviderMockRecorder {
	return m.recorder
}

// GetFirmwareUpdateStatus mocks base method.
func (m *MockFirmwareUpdateStatusProvider) GetFirmwareUpdateStatus(ctx context.Context) (*sdk.FirmwareUpdateStatus, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFirmwareUpdateStatus", ctx)
	ret0, _ := ret[0].(*sdk.FirmwareUpdateStatus)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetFirmwareUpdateStatus indicates an expected call of GetFirmwareUpdateStatus.
func (mr *MockFirmwareUpdateStatusProviderMockRecorder) GetFirmwareUpdateStatus(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFirmwareUpdateStatus", reflect.TypeOf((*MockFirmwareUpdateStatusProvider)(nil).GetFirmwareUpdateStatus), ctx)
}
