import type { InfraDeviceItem } from "../../types";

export const mockInfraDevices: InfraDeviceItem[] = [
  {
    id: "aus-b1-plc-01-zone-a",
    name: "Building 1 exhaust fans - Zone A",
    endpointKind: "fan_group",
    fanCount: 12,
    siteName: "Austin",
    buildingName: "Building 1",
    connectionType: "modbus_tcp",
    endpoint: "10.12.1.21",
    port: 502,
    status: "online",
    enabled: "auto",
    lastSeen: "Just now",
  },
  {
    id: "aus-b1-plc-01-zone-b",
    name: "Building 1 exhaust fans - Zone B",
    endpointKind: "fan_group",
    fanCount: 10,
    siteName: "Austin",
    buildingName: "Building 1",
    connectionType: "modbus_tcp",
    endpoint: "10.12.1.22",
    port: 502,
    status: "offline",
    enabled: "auto",
    lastSeen: "2 min ago",
  },
  {
    id: "aus-b2-bridge-07",
    name: "North wall fan group",
    endpointKind: "fan_group",
    fanCount: 8,
    siteName: "Austin",
    buildingName: "Building 2",
    connectionType: "mqtt_bridge",
    endpoint: "10.12.2.37",
    port: 44818,
    status: "offline",
    enabled: "off",
    lastSeen: "8 min ago",
  },
  {
    id: "den-b1-fan-03",
    name: "Rack row 3 intake fan",
    endpointKind: "single_fan",
    fanCount: 1,
    siteName: "Denver",
    buildingName: "Building 1",
    connectionType: "modbus_tcp",
    endpoint: "10.18.1.43",
    port: 502,
    status: "online",
    enabled: "auto",
    lastSeen: "Just now",
  },
  {
    id: "den-b1-plc-02-zone-c",
    name: "Building 1 exhaust fans - Zone C",
    endpointKind: "fan_group",
    fanCount: 16,
    siteName: "Denver",
    buildingName: "Building 1",
    connectionType: "modbus_tcp",
    endpoint: "10.18.1.58",
    port: 502,
    status: "offline",
    enabled: "auto",
    lastSeen: "35 min ago",
  },
  {
    id: "den-b5-bridge-11",
    name: "Evaporative cooling fan bank",
    endpointKind: "fan_group",
    fanCount: 20,
    siteName: "Denver",
    buildingName: "Building 5",
    connectionType: "mqtt_bridge",
    endpoint: "10.18.5.74",
    port: 44818,
    status: "offline",
    enabled: "auto",
    lastSeen: "1h ago",
  },
  {
    id: "mia-b2-fan-01",
    name: "South aisle booster fan",
    endpointKind: "single_fan",
    fanCount: 1,
    siteName: "Miami",
    buildingName: "Building 2",
    connectionType: "http_api",
    endpoint: "10.24.2.16",
    port: 502,
    status: "offline",
    enabled: "off",
    lastSeen: "4 min ago",
  },
  {
    id: "mia-b10-plc-04-zone-d",
    name: "Building 10 roof exhaust fans",
    endpointKind: "fan_group",
    fanCount: 14,
    siteName: "Miami",
    buildingName: "Building 10",
    connectionType: "modbus_tcp",
    endpoint: "10.24.10.42",
    port: 502,
    status: "online",
    enabled: "auto",
    lastSeen: "Just now",
  },
];
