// Code generated by MockGen. DO NOT EDIT.
// Source: infrastructure_device.go
//
// Generated by this command:
//
//	mockgen -source=infrastructure_device.go -destination=mocks/mock_infrastructure_device_store.go -package=mocks InfrastructureDeviceStore
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	models "github.com/block/proto-fleet/server/internal/domain/infrastructure/models"
	gomock "go.uber.org/mock/gomock"
)

// MockInfrastructureDeviceStore is a mock of InfrastructureDeviceStore interface.
type MockInfrastructureDeviceStore struct {
	ctrl     *gomock.Controller
	recorder *MockInfrastructureDeviceStoreMockRecorder
	isgomock struct{}
}

// MockInfrastructureDeviceStoreMockRecorder is the mock recorder for MockInfrastructureDeviceStore.
type MockInfrastructureDeviceStoreMockRecorder struct {
	mock *MockInfrastructureDeviceStore
}

// NewMockInfrastructureDeviceStore creates a new mock instance.
func NewMockInfrastructureDeviceStore(ctrl *gomock.Controller) *MockInfrastructureDeviceStore {
	mock := &MockInfrastructureDeviceStore{ctrl: ctrl}
	mock.recorder = &MockInfrastructureDeviceStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockInfrastructureDeviceStore) EXPECT() *MockInfrastructureDeviceStoreMockRecorder {
	return m.recorder
}

// CreateInfrastructureDevice mocks base method.
func (m *MockInfrastructureDeviceStore) CreateInfrastructureDevice(ctx context.Context, params models.CreateParams) (*models.Device, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateInfrastructureDevice", ctx, params)
	ret0, _ := ret[0].(*models.Device)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateInfrastructureDevice indicates an expected call of CreateInfrastructureDevice.
func (mr *MockInfrastructureDeviceStoreMockRecorder) CreateInfrastructureDevice(ctx, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateInfrastructureDevice", reflect.TypeOf((*MockInfrastructureDeviceStore)(nil).CreateInfrastructureDevice), ctx, params)
}

// GetInfrastructureDevice mocks base method.
func (m *MockInfrastructureDeviceStore) GetInfrastructureDevice(ctx context.Context, orgID, id int64) (*models.Device, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetInfrastructureDevice", ctx, orgID, id)
	ret0, _ := ret[0].(*models.Device)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetInfrastructureDevice indicates an expected call of GetInfrastructureDevice.
func (mr *MockInfrastructureDeviceStoreMockRecorder) GetInfrastructureDevice(ctx, orgID, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetInfrastructureDevice", reflect.TypeOf((*MockInfrastructureDeviceStore)(nil).GetInfrastructureDevice), ctx, orgID, id)
}

// ListInfrastructureDevices mocks base method.
func (m *MockInfrastructureDeviceStore) ListInfrastructureDevices(ctx context.Context, filter models.ListFilter) ([]models.Device, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListInfrastructureDevices", ctx, filter)
	ret0, _ := ret[0].([]models.Device)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListInfrastructureDevices indicates an expected call of ListInfrastructureDevices.
func (mr *MockInfrastructureDeviceStoreMockRecorder) ListInfrastructureDevices(ctx, filter any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListInfrastructureDevices", reflect.TypeOf((*MockInfrastructureDeviceStore)(nil).ListInfrastructureDevices), ctx, filter)
}

// SoftDeleteInfrastructureDevice mocks base method.
func (m *MockInfrastructureDeviceStore) SoftDeleteInfrastructureDevice(ctx context.Context, orgID, id, expectedSiteID int64) (*models.Device, bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SoftDeleteInfrastructureDevice", ctx, orgID, id, expectedSiteID)
	ret0, _ := ret[0].(*models.Device)
	ret1, _ := ret[1].(bool)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// SoftDeleteInfrastructureDevice indicates an expected call of SoftDeleteInfrastructureDevice.
func (mr *MockInfrastructureDeviceStoreMockRecorder) SoftDeleteInfrastructureDevice(ctx, orgID, id, expectedSiteID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SoftDeleteInfrastructureDevice", reflect.TypeOf((*MockInfrastructureDeviceStore)(nil).SoftDeleteInfrastructureDevice), ctx, orgID, id, expectedSiteID)
}

// UpdateInfrastructureDevice mocks base method.
func (m *MockInfrastructureDeviceStore) UpdateInfrastructureDevice(ctx context.Context, params models.UpdateParams) (*models.Device, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateInfrastructureDevice", ctx, params)
	ret0, _ := ret[0].(*models.Device)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateInfrastructureDevice indicates an expected call of UpdateInfrastructureDevice.
func (mr *MockInfrastructureDeviceStoreMockRecorder) UpdateInfrastructureDevice(ctx, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateInfrastructureDevice", reflect.TypeOf((*MockInfrastructureDeviceStore)(nil).UpdateInfrastructureDevice), ctx, params)
}
