// Code generated by MockGen. DO NOT EDIT.
// Source: building.go
//
// Generated by this command:
//
//	mockgen -source=building.go -destination=mocks/mock_building_store.go -package=mocks BuildingStore
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	models "github.com/block/proto-fleet/server/internal/domain/buildings/models"
	gomock "go.uber.org/mock/gomock"
)

// MockBuildingStore is a mock of BuildingStore interface.
type MockBuildingStore struct {
	ctrl     *gomock.Controller
	recorder *MockBuildingStoreMockRecorder
	isgomock struct{}
}

// MockBuildingStoreMockRecorder is the mock recorder for MockBuildingStore.
type MockBuildingStoreMockRecorder struct {
	mock *MockBuildingStore
}

// NewMockBuildingStore creates a new mock instance.
func NewMockBuildingStore(ctrl *gomock.Controller) *MockBuildingStore {
	mock := &MockBuildingStore{ctrl: ctrl}
	mock.recorder = &MockBuildingStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBuildingStore) EXPECT() *MockBuildingStoreMockRecorder {
	return m.recorder
}

// AssignDevicesToBuilding mocks base method.
func (m *MockBuildingStore) AssignDevicesToBuilding(ctx context.Context, orgID int64, targetBuildingID *int64, deviceIdentifiers []string) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AssignDevicesToBuilding", ctx, orgID, targetBuildingID, deviceIdentifiers)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AssignDevicesToBuilding indicates an expected call of AssignDevicesToBuilding.
func (mr *MockBuildingStoreMockRecorder) AssignDevicesToBuilding(ctx, orgID, targetBuildingID, deviceIdentifiers any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AssignDevicesToBuilding", reflect.TypeOf((*MockBuildingStore)(nil).AssignDevicesToBuilding), ctx, orgID, targetBuildingID, deviceIdentifiers)
}

// BuildingBelongsToOrg mocks base method.
func (m *MockBuildingStore) BuildingBelongsToOrg(ctx context.Context, orgID, id int64) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BuildingBelongsToOrg", ctx, orgID, id)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BuildingBelongsToOrg indicates an expected call of BuildingBelongsToOrg.
func (mr *MockBuildingStoreMockRecorder) BuildingBelongsToOrg(ctx, orgID, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BuildingBelongsToOrg", reflect.TypeOf((*MockBuildingStore)(nil).BuildingBelongsToOrg), ctx, orgID, id)
}

// BuildingsByIDs mocks base method.
func (m *MockBuildingStore) BuildingsByIDs(ctx context.Context, orgID int64, ids []int64) ([]int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BuildingsByIDs", ctx, orgID, ids)
	ret0, _ := ret[0].([]int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BuildingsByIDs indicates an expected call of BuildingsByIDs.
func (mr *MockBuildingStoreMockRecorder) BuildingsByIDs(ctx, orgID, ids any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BuildingsByIDs", reflect.TypeOf((*MockBuildingStore)(nil).BuildingsByIDs), ctx, orgID, ids)
}

// CascadeDevicesSiteForBuilding mocks base method.
func (m *MockBuildingStore) CascadeDevicesSiteForBuilding(ctx context.Context, orgID int64, deviceIdentifiers []string, targetSiteID *int64) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CascadeDevicesSiteForBuilding", ctx, orgID, deviceIdentifiers, targetSiteID)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CascadeDevicesSiteForBuilding indicates an expected call of CascadeDevicesSiteForBuilding.
func (mr *MockBuildingStoreMockRecorder) CascadeDevicesSiteForBuilding(ctx, orgID, deviceIdentifiers, targetSiteID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CascadeDevicesSiteForBuilding", reflect.TypeOf((*MockBuildingStore)(nil).CascadeDevicesSiteForBuilding), ctx, orgID, deviceIdentifiers, targetSiteID)
}

// CascadeDirectDeviceSitesByBuildings mocks base method.
func (m *MockBuildingStore) CascadeDirectDeviceSitesByBuildings(ctx context.Context, orgID int64, buildingIDs []int64, targetSiteID *int64) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CascadeDirectDeviceSitesByBuildings", ctx, orgID, buildingIDs, targetSiteID)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CascadeDirectDeviceSitesByBuildings indicates an expected call of CascadeDirectDeviceSitesByBuildings.
func (mr *MockBuildingStoreMockRecorder) CascadeDirectDeviceSitesByBuildings(ctx, orgID, buildingIDs, targetSiteID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CascadeDirectDeviceSitesByBuildings", reflect.TypeOf((*MockBuildingStore)(nil).CascadeDirectDeviceSitesByBuildings), ctx, orgID, buildingIDs, targetSiteID)
}

// ClearDeviceBuildingsByBuilding mocks base method.
func (m *MockBuildingStore) ClearDeviceBuildingsByBuilding(ctx context.Context, orgID, buildingID int64) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ClearDeviceBuildingsByBuilding", ctx, orgID, buildingID)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ClearDeviceBuildingsByBuilding indicates an expected call of ClearDeviceBuildingsByBuilding.
func (mr *MockBuildingStoreMockRecorder) ClearDeviceBuildingsByBuilding(ctx, orgID, buildingID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ClearDeviceBuildingsByBuilding", reflect.TypeOf((*MockBuildingStore)(nil).ClearDeviceBuildingsByBuilding), ctx, orgID, buildingID)
}

// ClearDeviceBuildingsBySite mocks base method.
func (m *MockBuildingStore) ClearDeviceBuildingsBySite(ctx context.Context, orgID, siteID int64) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ClearDeviceBuildingsBySite", ctx, orgID, siteID)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ClearDeviceBuildingsBySite indicates an expected call of ClearDeviceBuildingsBySite.
func (mr *MockBuildingStoreMockRecorder) ClearDeviceBuildingsBySite(ctx, orgID, siteID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ClearDeviceBuildingsBySite", reflect.TypeOf((*MockBuildingStore)(nil).ClearDeviceBuildingsBySite), ctx, orgID, siteID)
}

// ClearDeviceBuildingsOnSiteMismatch mocks base method.
func (m *MockBuildingStore) ClearDeviceBuildingsOnSiteMismatch(ctx context.Context, orgID int64, deviceIdentifiers []string, targetSiteID *int64) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ClearDeviceBuildingsOnSiteMismatch", ctx, orgID, deviceIdentifiers, targetSiteID)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ClearDeviceBuildingsOnSiteMismatch indicates an expected call of ClearDeviceBuildingsOnSiteMismatch.
func (mr *MockBuildingStoreMockRecorder) ClearDeviceBuildingsOnSiteMismatch(ctx, orgID, deviceIdentifiers, targetSiteID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ClearDeviceBuildingsOnSiteMismatch", reflect.TypeOf((*MockBuildingStore)(nil).ClearDeviceBuildingsOnSiteMismatch), ctx, orgID, deviceIdentifiers, targetSiteID)
}

// CreateBuilding mocks base method.
func (m *MockBuildingStore) CreateBuilding(ctx context.Context, params models.CreateParams) (*models.Building, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateBuilding", ctx, params)
	ret0, _ := ret[0].(*models.Building)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateBuilding indicates an expected call of CreateBuilding.
func (mr *MockBuildingStoreMockRecorder) CreateBuilding(ctx, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateBuilding", reflect.TypeOf((*MockBuildingStore)(nil).CreateBuilding), ctx, params)
}

// FindDeviceBuildingConflicts mocks base method.
func (m *MockBuildingStore) FindDeviceBuildingConflicts(ctx context.Context, orgID int64, deviceIdentifiers []string) (map[string]int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindDeviceBuildingConflicts", ctx, orgID, deviceIdentifiers)
	ret0, _ := ret[0].(map[string]int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindDeviceBuildingConflicts indicates an expected call of FindDeviceBuildingConflicts.
func (mr *MockBuildingStoreMockRecorder) FindDeviceBuildingConflicts(ctx, orgID, deviceIdentifiers any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindDeviceBuildingConflicts", reflect.TypeOf((*MockBuildingStore)(nil).FindDeviceBuildingConflicts), ctx, orgID, deviceIdentifiers)
}

// FindDevicesInBuildingLessPlacedRacks mocks base method.
func (m *MockBuildingStore) FindDevicesInBuildingLessPlacedRacks(ctx context.Context, orgID int64, deviceIdentifiers []string) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindDevicesInBuildingLessPlacedRacks", ctx, orgID, deviceIdentifiers)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindDevicesInBuildingLessPlacedRacks indicates an expected call of FindDevicesInBuildingLessPlacedRacks.
func (mr *MockBuildingStoreMockRecorder) FindDevicesInBuildingLessPlacedRacks(ctx, orgID, deviceIdentifiers any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindDevicesInBuildingLessPlacedRacks", reflect.TypeOf((*MockBuildingStore)(nil).FindDevicesInBuildingLessPlacedRacks), ctx, orgID, deviceIdentifiers)
}

// GetBuilding mocks base method.
func (m *MockBuildingStore) GetBuilding(ctx context.Context, orgID, id int64) (*models.Building, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBuilding", ctx, orgID, id)
	ret0, _ := ret[0].(*models.Building)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBuilding indicates an expected call of GetBuilding.
func (mr *MockBuildingStoreMockRecorder) GetBuilding(ctx, orgID, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBuilding", reflect.TypeOf((*MockBuildingStore)(nil).GetBuilding), ctx, orgID, id)
}

// GetBuildingSiteID mocks base method.
func (m *MockBuildingStore) GetBuildingSiteID(ctx context.Context, orgID, buildingID int64) (*int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBuildingSiteID", ctx, orgID, buildingID)
	ret0, _ := ret[0].(*int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBuildingSiteID indicates an expected call of GetBuildingSiteID.
func (mr *MockBuildingStoreMockRecorder) GetBuildingSiteID(ctx, orgID, buildingID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBuildingSiteID", reflect.TypeOf((*MockBuildingStore)(nil).GetBuildingSiteID), ctx, orgID, buildingID)
}

// ListBuildingRacks mocks base method.
func (m *MockBuildingStore) ListBuildingRacks(ctx context.Context, orgID, buildingID int64, pageSize int32, pageToken string) ([]models.BuildingRack, string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListBuildingRacks", ctx, orgID, buildingID, pageSize, pageToken)
	ret0, _ := ret[0].([]models.BuildingRack)
	ret1, _ := ret[1].(string)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListBuildingRacks indicates an expected call of ListBuildingRacks.
func (mr *MockBuildingStoreMockRecorder) ListBuildingRacks(ctx, orgID, buildingID, pageSize, pageToken any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListBuildingRacks", reflect.TypeOf((*MockBuildingStore)(nil).ListBuildingRacks), ctx, orgID, buildingID, pageSize, pageToken)
}

// ListBuildings mocks base method.
func (m *MockBuildingStore) ListBuildings(ctx context.Context, filter models.ListFilter) ([]models.BuildingWithCounts, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListBuildings", ctx, filter)
	ret0, _ := ret[0].([]models.BuildingWithCounts)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListBuildings indicates an expected call of ListBuildings.
func (mr *MockBuildingStoreMockRecorder) ListBuildings(ctx, filter any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListBuildings", reflect.TypeOf((*MockBuildingStore)(nil).ListBuildings), ctx, filter)
}

// ListRacksOutsideBuildingBounds mocks base method.
func (m *MockBuildingStore) ListRacksOutsideBuildingBounds(ctx context.Context, orgID, buildingID int64, newAisles, newRacksPerAisle int32) ([]models.BuildingRack, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListRacksOutsideBuildingBounds", ctx, orgID, buildingID, newAisles, newRacksPerAisle)
	ret0, _ := ret[0].([]models.BuildingRack)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListRacksOutsideBuildingBounds indicates an expected call of ListRacksOutsideBuildingBounds.
func (mr *MockBuildingStoreMockRecorder) ListRacksOutsideBuildingBounds(ctx, orgID, buildingID, newAisles, newRacksPerAisle any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListRacksOutsideBuildingBounds", reflect.TypeOf((*MockBuildingStore)(nil).ListRacksOutsideBuildingBounds), ctx, orgID, buildingID, newAisles, newRacksPerAisle)
}

// SetRackBuildingPosition mocks base method.
func (m *MockBuildingStore) SetRackBuildingPosition(ctx context.Context, orgID, rackID int64, aisleIndex, positionInAisle *int32) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetRackBuildingPosition", ctx, orgID, rackID, aisleIndex, positionInAisle)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetRackBuildingPosition indicates an expected call of SetRackBuildingPosition.
func (mr *MockBuildingStoreMockRecorder) SetRackBuildingPosition(ctx, orgID, rackID, aisleIndex, positionInAisle any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetRackBuildingPosition", reflect.TypeOf((*MockBuildingStore)(nil).SetRackBuildingPosition), ctx, orgID, rackID, aisleIndex, positionInAisle)
}

// SetRackBuildingPositionBulkClear mocks base method.
func (m *MockBuildingStore) SetRackBuildingPositionBulkClear(ctx context.Context, orgID int64, rackIDs []int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetRackBuildingPositionBulkClear", ctx, orgID, rackIDs)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetRackBuildingPositionBulkClear indicates an expected call of SetRackBuildingPositionBulkClear.
func (mr *MockBuildingStoreMockRecorder) SetRackBuildingPositionBulkClear(ctx, orgID, rackIDs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetRackBuildingPositionBulkClear", reflect.TypeOf((*MockBuildingStore)(nil).SetRackBuildingPositionBulkClear), ctx, orgID, rackIDs)
}

// SetRackBuildingPositionBulkPlace mocks base method.
func (m *MockBuildingStore) SetRackBuildingPositionBulkPlace(ctx context.Context, orgID int64, rackIDs []int64, aisleIndexes, positionInAisles []int32) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetRackBuildingPositionBulkPlace", ctx, orgID, rackIDs, aisleIndexes, positionInAisles)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetRackBuildingPositionBulkPlace indicates an expected call of SetRackBuildingPositionBulkPlace.
func (mr *MockBuildingStoreMockRecorder) SetRackBuildingPositionBulkPlace(ctx, orgID, rackIDs, aisleIndexes, positionInAisles any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetRackBuildingPositionBulkPlace", reflect.TypeOf((*MockBuildingStore)(nil).SetRackBuildingPositionBulkPlace), ctx, orgID, rackIDs, aisleIndexes, positionInAisles)
}

// SoftDeleteBuilding mocks base method.
func (m *MockBuildingStore) SoftDeleteBuilding(ctx context.Context, orgID, id int64) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SoftDeleteBuilding", ctx, orgID, id)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SoftDeleteBuilding indicates an expected call of SoftDeleteBuilding.
func (mr *MockBuildingStoreMockRecorder) SoftDeleteBuilding(ctx, orgID, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SoftDeleteBuilding", reflect.TypeOf((*MockBuildingStore)(nil).SoftDeleteBuilding), ctx, orgID, id)
}

// UnassignRacksFromBuilding mocks base method.
func (m *MockBuildingStore) UnassignRacksFromBuilding(ctx context.Context, orgID, buildingID int64) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UnassignRacksFromBuilding", ctx, orgID, buildingID)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UnassignRacksFromBuilding indicates an expected call of UnassignRacksFromBuilding.
func (mr *MockBuildingStoreMockRecorder) UnassignRacksFromBuilding(ctx, orgID, buildingID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UnassignRacksFromBuilding", reflect.TypeOf((*MockBuildingStore)(nil).UnassignRacksFromBuilding), ctx, orgID, buildingID)
}

// UpdateBuilding mocks base method.
func (m *MockBuildingStore) UpdateBuilding(ctx context.Context, params models.UpdateParams) (*models.Building, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateBuilding", ctx, params)
	ret0, _ := ret[0].(*models.Building)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateBuilding indicates an expected call of UpdateBuilding.
func (mr *MockBuildingStoreMockRecorder) UpdateBuilding(ctx, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateBuilding", reflect.TypeOf((*MockBuildingStore)(nil).UpdateBuilding), ctx, params)
}
