name: Pull Request

on: pull_request_target

permissions:
  contents: read
  repository-projects: read
  pull-requests: write

jobs:
  triage:
    name: Triage
    runs-on: ubuntu-latest

    steps:
      - name: Apply labels
        uses: actions/labeler@f27b608878404679385c85cfa523b85ccb86e213 # v6.1.0
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
          sync-labels: true

  auto-assign:
    name: Auto-Assign
    runs-on: ubuntu-latest
    if: github.actor != 'dependabot[bot]'

    steps:
      - name: Assign PR to Creator
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_REPO: ${{ github.repository }}
        run: |
          gh pr edit ${{ github.event.pull_request.number }} --add-assignee ${{ github.actor }}
